name: alpine-tools

on: workflow_dispatch
#   push:
#     branches: [ main ]
#     paths: [ "repos/alpine-tools/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: khucgo/alpile-tools
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set name to Docker image
      id: vars
      run: |
        echo "::set-output name=REPO_TAG::$(date +%Y%m%d)"
        echo "Container image: $REPO_NAME:$(date +%Y%m%d)"
    - name: Build the Docker image
      run: docker build ./repos/alpine-tools/ --tag $REPO_NAME:${{ steps.vars.outputs.REPO_TAG }}
    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push $REPO_NAME:${{ steps.vars.outputs.REPO_TAG }}
