name: alpine-tools

on:
  push:
    branches: [ main ]
    paths: [ "repos/alpine-tools/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./repos/alpine-tools/ --tag khucgo/alpine-tools:$(date +%s)
